# Generated by Django 3.2.6 on 2021-08-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='webex_email',
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
    ]
