# Generated by Django 3.2.6 on 2021-08-12 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rename_file


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('carbrand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carbrand')),
            ],
        ),
        migrations.CreateModel(
            name='UserCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='price per day')),
                ('is_available', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to=rename_file.rename_car_pic)),
                ('carbrand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.carbrand', verbose_name='Brand')),
                ('carmodel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.carmodel', verbose_name='Model')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
