# Generated by Django 3.2.6 on 2021-08-12 05:24

import bookings.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_date', models.DateField(auto_now_add=True)),
                ('destination', models.CharField(blank=True, max_length=150, null=True)),
                ('returning_date', models.DateField(validators=[bookings.validators.is_future_date])),
                ('is_returned', models.BooleanField(default=False)),
                ('is_rated', models.BooleanField(default=False)),
                ('user_rating', models.IntegerField(default=0)),
                ('booked_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('usercar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.usercar')),
            ],
        ),
    ]
